# Generated by Django 6.0.4 on 2026-04-30 06:36

import chatbot.models
import chatbot.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan_name",
                    models.CharField(
                        choices=[
                            ("FREE", "Free"),
                            ("STANDARD", "Standard"),
                            ("PRO", "Pro"),
                        ],
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("plan_description", models.CharField(max_length=255)),
                ("token_limit", models.PositiveIntegerField()),
                ("price", models.PositiveIntegerField()),
                ("features", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.AlterField(
            model_name="conversation",
            name="title",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name="PurchasePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tokens_used", models.PositiveIntegerField(default=0)),
                (
                    "usage_end_date",
                    models.DateTimeField(default=chatbot.utils.default_usage_end),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        default=chatbot.models.Plan.get_free_plan,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chatbot.plan",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
